name: housingsociety
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.0
  flutter_spinkit: ^5.0.0
  provider: ^5.0.0
  modal_bottom_sheet: ^2.0.0
  image_picker: 0.8.5
  url_launcher: 6.0.20
  percent_indicator: ^3.0.1
  flutter_tts: ^3.1.0
  translator: ^0.1.7
  rake: ^1.0.1
  pie_chart: ^5.0.0
  connectivity: 3.0.6
  firebase_core: 1.14.1
  firebase_auth: 3.3.14
  cloud_firestore: 3.1.12
  firebase_storage: 10.2.12
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/default_profile_pic.jpg
  uses-material-design: true

